In [20]:
from sklearn import datasets
import pandas as pd

In [21]:
iris = datasets.load_iris()
X = iris.data
Y = iris.target

In [22]:
Df = pd.DataFrame()

In [26]:
Df["X"] = X.tolist()
Df["Y"] = Y.tolist()

In [30]:
d_dash = Df.sample(frac=0.7)

In [31]:
d_dash.shape

(105, 2)

In [49]:
orig_index = sorted(Df.index.tolist())
z = sorted(d_dash.index.tolist())

In [54]:
y = sorted(set(orig_index) - set(z))
print(y)

[1, 2, 15, 16, 18, 19, 25, 26, 27, 28, 31, 34, 36, 41, 46, 47, 50, 52, 53, 60, 62, 63, 69, 75, 78, 83, 88, 89, 95, 96, 99, 101, 105, 108, 113, 118, 121, 127, 128, 129, 131, 132, 134, 137, 142]

In [55]:
print(y,z)

[1, 2, 15, 16, 18, 19, 25, 26, 27, 28, 31, 34, 36, 41, 46, 47, 50, 52, 53, 60, 62, 63, 69, 75, 78, 83, 88, 89, 95, 96, 99, 101, 105, 108, 113, 118, 121, 127, 128, 129, 131, 132, 134, 137, 142] [0, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 17, 20, 21, 22, 23, 24, 29, 30, 32, 33, 35, 37, 38, 39, 40, 42, 43, 44, 45, 48, 49, 51, 54, 55, 56, 57, 58, 59, 61, 64, 65, 66, 67, 68, 70, 71, 72, 73, 74, 76, 77, 79, 80, 81, 82, 84, 85, 86, 87, 90, 91, 92, 93, 94, 97, 98, 100, 102, 103, 104, 106, 107, 109, 110, 111, 112, 114, 115, 116, 117, 119, 120, 122, 123, 124, 125, 126, 130, 133, 135, 136, 138, 139, 140, 141, 143, 144, 145, 146, 147, 148, 149]

In [63]:
Df.ix[y]

                        X  Y
1    [4.9, 3.0, 1.4, 0.2]  0
2    [4.7, 3.2, 1.3, 0.2]  0
15   [5.7, 4.4, 1.5, 0.4]  0
16   [5.4, 3.9, 1.3, 0.4]  0
18   [5.7, 3.8, 1.7, 0.3]  0
19   [5.1, 3.8, 1.5, 0.3]  0
25   [5.0, 3.0, 1.6, 0.2]  0
26   [5.0, 3.4, 1.6, 0.4]  0
27   [5.2, 3.5, 1.5, 0.2]  0
28   [5.2, 3.4, 1.4, 0.2]  0
31   [5.4, 3.4, 1.5, 0.4]  0
34   [4.9, 3.1, 1.5, 0.1]  0
36   [5.5, 3.5, 1.3, 0.2]  0
41   [4.5, 2.3, 1.3, 0.3]  0
46   [5.1, 3.8, 1.6, 0.2]  0
47   [4.6, 3.2, 1.4, 0.2]  0
50   [7.0, 3.2, 4.7, 1.4]  1
52   [6.9, 3.1, 4.9, 1.5]  1
53   [5.5, 2.3, 4.0, 1.3]  1
60   [5.0, 2.0, 3.5, 1.0]  1
62   [6.0, 2.2, 4.0, 1.0]  1
63   [6.1, 2.9, 4.7, 1.4]  1
69   [5.6, 2.5, 3.9, 1.1]  1
75   [6.6, 3.0, 4.4, 1.4]  1
78   [6.0, 2.9, 4.5, 1.5]  1
83   [6.0, 2.7, 5.1, 1.6]  1
88   [5.6, 3.0, 4.1, 1.3]  1
89   [5.5, 2.5, 4.0, 1.3]  1
95   [5.7, 3.0, 4.2, 1.2]  1
96   [5.7, 2.9, 4.2, 1.3]  1
99   [5.7, 2.8, 4.1, 1.3]  1
101  [5.8, 2.7, 5.1, 1.9]  2
105  [7.6, 3.0, 6.6, 2.1]  2
108  [6.7, 2.5, 5.8, 1.8]  2
113  [5.7, 2.5, 5.0, 2.0]  2
118  [7.7, 2.6, 6.9, 2.3]  2
121  [5.6, 2.8, 4.9, 2.0]  2
127  [6.1, 3.0, 4.9, 1.8]  2
128  [6.4, 2.8, 5.6, 2.1]  2
129  [7.2, 3.0, 5.8, 1.6]  2
131  [7.9, 3.8, 6.4, 2.0]  2
132  [6.4, 2.8, 5.6, 2.2]  2
134  [6.1, 2.6, 5.6, 1.4]  2
137  [6.4, 3.1, 5.5, 1.8]  2
142  [5.8, 2.7, 5.1, 1.9]  2